#!/bin/bash
echo "================================="
echo "   PM2 Service Monitor Access    "
echo "================================="
echo ""
echo "🔧 PM2 Monitor Server: http://localhost:3001"
echo "📊 Status API: http://localhost:3001/monitor/status"
echo ""
echo "Available Monitoring Options:"
echo ""
echo "1. View PM2 Process Status:"
echo "   curl http://localhost:3001/monitor/status | jq"
echo ""
echo "2. View Service Logs:"
echo "   curl http://localhost:3001/monitor/logs/poolDataSync"
echo ""
echo "3. Admin Dashboard (Main App):"
echo "   http://localhost:5000/admin (requires login)"
echo ""
echo "4. Live Monitoring Scripts:"
echo "   ./monitor-pm2-status.sh       - PM2 process monitoring"
echo "   ./monitor-pooldata-live.sh    - Pool data sync monitoring"
echo "   ./monitor-live-updates.sh     - Real-time updates"
echo ""
echo "🚀 Starting PM2 monitor server..."
pm2 list
echo ""
echo "📋 Current services status:"
curl -s http://localhost:3001/monitor/status 2>/dev/null | jq '.[].name' || echo "PM2 monitor not responding"
